#!/usr/bin/node

const fs = require('fs')
const { exec } = require("child_process");

/**
 * This will only works if the project folder is in the parent folder
 * This is not global fs solution!
 */
console.log(__dirname);
fs.copyFile('./framework/src/artisan', './artisan', (err) => {
    err ? console.log(err) : ''
})

console.log("\x1b[32m%s\x1b[0m", "Framework installed successfully!");